### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by CrazyWords1** [Anarchick/skript-packet#6]
example:
```
effect change client side equipment %string% of %entity% to %itemstack% for %players%:
    trigger:
        set {_slot} to expression-1 in upper case
        {_slot} is "CHEST" or "FEET" or "HEAD" or "LEGS" or "MAINHAND" or "OFFHAND"
        set {_entity} to expression-2
        {_entity} is an entity
        set {_item} to expression-3 ? air
        set {_nmsItem} to nms of (random item out of {_item})
        {_nmsItem} is set
        set {_players::*} to expression-4
        set {_packet} to new play_server_entity_equipment packet
        set field 0 of {_packet} to id of {_entity}
        set {_itemSlot} to enum {_slot} from nms class "EnumItemSlot"
        set {_pair} to pair {_itemSlot} with {_nmsItem}
        set {_data} to {_pair} as arraylist
        set field 1 of {_packet} to {_data}
        send {_players::*} packet {_packet}
command /test1:
    permission: core.command.use
    trigger:
        change client side equipment "head" of {crazy} to diamond helmet for all players
```

The error
```
[18:57:04] [Server thread/INFO]: _CrazyWords_ [961c8f42-43a5-363d-8244-3f64678bc89c]: /test1
[18:57:04] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to Skript v2.6-beta2
java.lang.NoSuchMethodError: 'java.lang.Class com.comphenix.protocol.utility.MinecraftReflection.getNullableNMS(java.lang.String)'
	at fr.anarchick.skriptpacket.elements.expressions.ExprEnum.get(ExprEnum.java:77) ~[?:?]
	at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99) ~[?:?]
	at ch.njol.skript.effects.EffChange.execute(EffChange.java:274) ~[?:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:51) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
	at com.btk5h.skriptmirror.skript.custom.effect.CustomEffect.invokeEffect(CustomEffect.java:55) ~[?:?]
	at com.btk5h.skriptmirror.skript.custom.effect.CustomEffect.walk(CustomEffect.java:30) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:289) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:250) ~[?:?]
	at ch.njol.skript.command.Commands.handleCommand(Commands.java:258) ~[?:?]
	at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:175) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2259) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2082) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2035) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1325) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1318) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1294) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1138) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[18:57:04] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'test1' in plugin Skript v2.6-beta2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2267) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2082) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2035) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1325) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1318) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1294) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1138) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoSuchMethodError: 'java.lang.Class com.comphenix.protocol.utility.MinecraftReflection.getNullableNMS(java.lang.String)'
	at fr.anarchick.skriptpacket.elements.expressions.ExprEnum.get(ExprEnum.java:77) ~[?:?]
	at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99) ~[?:?]
	at ch.njol.skript.effects.EffChange.execute(EffChange.java:274) ~[?:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:51) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
	at com.btk5h.skriptmirror.skript.custom.effect.CustomEffect.invokeEffect(CustomEffect.java:55) ~[?:?]
	at com.btk5h.skriptmirror.skript.custom.effect.CustomEffect.walk(CustomEffect.java:30) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:289) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:250) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:194) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	... 19 more
```

**Comment by Anarchick** [comment]
Hi, what is your version of ProtocolLib ? Works with v4.6.0 for 1.16.5,
the method getNullableNMS() has changed between 4.6 and 4.7.

Thanks for your report, fix in next release, you can use skript-reflect as hotfix :
```as
import:
    net.minecraft.server.v1_16_R3.EnumItemSlot

    [CODE]
    set {_itemSlot} to EnumItemSlot.valueOf({_slot})

````

**Comment by CrazyWords1** [comment]
I found your code in skript-reflect discord chat, work normal without bugs
```
effect client side equipment %string% of %entity% to %itemstack% for %players%:
	trigger:
		set {_slot} to expression-1
		{_slot} is "CHEST" or "FEET" or "HEAD" or "LEGS" or "MAINHAND" or "OFFHAND"
		set {_entity} to expression-2
		set {_item} to expression-3 ? air
		set {_item} to random item out of {_item}
		set {_players::*} to expression-4
		set {_packet} to new play_server_entity_equipment packet
		set field 0 of {_packet} to id of {_entity}
		set {_data} to new ArrayList()
		{_data}.add(new Pair(ItemSlot.valueOf({_slot}) and {_item}))
		{_packet}.getSlotStackPairLists().write(0, {_data})
		loop {_players::*}:
			send loop-value packet {_packet}
```

**Comment by Anarchick** [comment]
I don't recommand to use this old method. It's too much reflection. You should use my hotfix since I upload the release v1.3

**Comment by Anarchick** [comment]
Solve with 2.0
